"use client";

import type { ImageLoaderProps } from "next/image";

// Photos are referenced as /photos/<name>.jpg and resolve to the WebP widths
// generated by scripts/optimize-images.mts. Every width Next asks for comes
// from image-sizes.json, so a matching file always exists.
export default function imageLoader({ src, width }: ImageLoaderProps) {
  const photo = src.match(/^\/photos\/([\w-]+)\.jpe?g$/);
  return photo ? `/photos/${photo[1]}-${width}.webp` : src;
}
